### ISSUE TITLE
Issue accessing @@color-@{name} properties outside the library

### ISSUE THREAD

**Issue by diosney** [zavoloklom/material-design-color-palette#5]
The issue is stated at http://stackoverflow.com/q/31475629/881286.

Can you help with it?

Thanks

**Comment by diosney** [comment]
Already solved.

``` less
.color-@{color}-@{step} {
    @buffer: 'color-@{step}';
    @color: @@buffer;

    color: @@color;
}
```
