### ISSUE TITLE
[Request] Border Colors

### ISSUE THREAD

**Issue by mouse0270** [zavoloklom/material-design-color-palette#7]
It would be nice to also include a `border-color` option as will.

``` css
.border-teal {
    border-color: rgb(0, 150, 136)
}
```
